# ~/.config/mango/config.conf

exec-once=dms run

# ============ APPS ============
bind=SUPER,w,spawn,AyuGram
bind=SUPER,w,spawn,vivaldi
bind=SUPER,t,spawn,wezterm
#bind=SUPER,d,spawn,dms ipc call spotlight toggle
bind=SUPER,e,spawn,dms ipc call spotlight-bar toggle

# ============ SESSION ============
bind=SUPER,Escape,killclient,
bind=SUPER+SHIFT,m,quit,
bind=SUPER,r,reload_config
bind=SUPER,l,spawn,dms ipc call lock lock
bind=SUPER,p,spawn,dms ipc call powermenu toggle

# ============ WINDOW STATE ============
bind=ALT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
bind=ALT,backslash,togglefloating,
bind=ALT,a,togglemaximizescreen,
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=SUPER,i,minimized,
bind=SUPER+SHIFT,i,restore_minimized,
bind=ALT,z,toggle_scratchpad,

# ============ FOCUS / MOVE (hjkl) ============
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down
bind=SUPER,Tab,focusstack,next

bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down

# ============ TAGS (workspaces) ============
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5

bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5

# ============ MOUSE ============
mousebind=SUPER+drag,movewin
mousebind=SUPER+SHIFT+drag,resizewin

# ============ DMS: AUDIO/MEDIA ============
bind=NONE,XF86AudioRaiseVolume,spawn,dms ipc call audio increment 3
bind=NONE,XF86AudioLowerVolume,spawn,dms ipc call audio decrement 3
bind=NONE,XF86AudioMute,spawn,dms ipc call audio mute
bind=NONE,XF86AudioPlay,spawn,dms ipc call mpris playPause
bind=NONE,XF86AudioNext,spawn,dms ipc call mpris next
bind=NONE,XF86AudioPrev,spawn,dms ipc call mpris previous

# ============ DMS: BRIGHTNESS ============
bind=NONE,XF86MonBrightnessUp,spawn,dms ipc call brightness increment 5
bind=NONE,XF86MonBrightnessDown,spawn,dms ipc call brightness decrement 5

# ============ KEYBOARD ============
xkb_rules_layout=us,ru

# ============ DMS: UI PANELS ============
bind=SUPER,space,switch_keyboard_layout
bind=SUPER,s,spawn,dms ipc call launcher toggle
bind=SUPER,comma,spawn,dms ipc call settings toggle
bind=SUPER,n,spawn,dms ipc call notifications toggle
bind=SUPER,c,spawn,dms ipc call control-center toggle
bind=SUPER,slash,spawn,dms ipc call keybinds toggle

# ============ SCREENSHOT ============
bind=NONE,Print,spawn,dms ipc call screenshot begin
