exec-once=dms run 

mousebind=SUPER+drag,movewin

bind=SUPER,q,killclient,
bind=SUPER,t,spawn,wezterm
bind=SUPER,d,spawn,wmenu-run -l 10
bind=SUPER,space,spawn,dms ipc call spotlight toggle
bind=SUPER,comma,spawn,dms ipc call settings toggle
bind=NONE,XF86AudioRaiseVolume,spawn,dms ipc call audio increment 3
bind=NONE,XF86AudioLowerVolume,spawn,dms ipc call audio decrement 3
bind=NONE,XF86AudioMute,spawn,dms ipc call audio mute
bind=NONE,XF86MonBrightnessUp,spawn,dms ipc call brightness increment 5
bind=NONE,XF86MonBrightnessDown,spawn,dms ipc call brightness decrement 5
bind=SUPER,r,reload_config
