 [opener]
 edit = [
  { run = "wezterm -e hx $@", block = false, desc = "helix" }
 ]

 [open]
 rules = [
 { name = "*.nix", use = "edit" },
 { name = "*.toml", use = "edit" },
 { name = "*.md", use = "edit" },
 {mime = "*", use = "edit"}
]

