# ═══════════════════════════════════════════════════════
# HYPRLOCK — BlazinLocki style (v0.9.5)
# ═══════════════════════════════════════════════════════

general {
    ignore_empty_input = true
}


# BACKGROUND

background {
    monitor =
    path = /home/kori/Wallpapers/Street.jpg
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 1
    blur_size = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.8916
    vibrancy_darkness = 0.0
}


# TIME

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(216, 192, 228, 0.7)
    font_size = 130
    font_family = Noto Sans SC ExtraBold
    position = 0, 300
    halign = center
    valign = center
}


# DATE

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %d %B")"
    color = rgba(216, 192, 228, 0.7)
    font_size = 30
    font_family = Noto Sans SC Bold
    position = 0, 180
    halign = center
    valign = center
}


# USER-BOX

shape {
    monitor =
    size = 29%, 28%
    color = rgba(255, 255, 255, .1)
    rounding = 20
    border_size = 2
    border_color = rgba(210, 125, 227, 1.0) rgba(125, 186, 227, 1.0) 45deg
    position = 0, -80
    halign = center
    valign = center
}


# PROFILE-PICTURE

image {
    monitor =
    path = /home/kori/Wallpapers/𝓹𝓪𝓽𝓬𝓱𝓸𝓾𝓵𝓲 𝓴𝓷𝓸𝔀𝓵𝓮𝓭𝓰𝓮.jpeg
    border_color = rgba(125, 186, 227, 1.0) rgba(210, 125, 227, 1.0) 45deg
    border_size = 2
    size = 100
    rounding = -1
    reload_time = -1
    position = -110, -60
    halign = center
    valign = center
}


# USER-FIELD

shape {
    monitor =
    size = 10%, 3.5%
    color = rgba(255, 255, 255, 0.11)
    rounding = 500
    border_size = 2
    border_color = rgba(210, 125, 227, 1.0) rgba(125, 186, 227, 1.0) 45deg
    position = 180, -45
    halign = center
    valign = center
}


# USERNAME

label {
    monitor =
    text = <span> <b>✦ $USER </b> </span>
    text_align = center
    color = rgba(200, 200, 200, 1.0)
    font_size = 14
    font_family = Noto Sans SC Bold
    position = 180, -46
    halign = center
    valign = center
}


# PASSWD-FIELD

input-field {
    monitor =
    size = 10%, 3.5%
    outline_thickness = 2
    outer_color = rgba(125, 186, 227, 1.0) rgba(210, 125, 227, 1.0) 45deg
    inner_color = rgba(255, 255, 255, 0.11)
    font_color = rgba(200, 200, 200, 1.0)
    fade_on_empty = false
    check_color = rgba(210, 125, 227, 1.0) rgba(125, 186, 227, 1.0) 45deg
    position = 180, -125
    halign = center
    valign = center
    placeholder_text = <i> <b>✦ passwd </b> </i>
    fail_text = <i> <b> bad gril ($ATTEMPTS) </b> </i>
}
