[include]
files = []

[general]
autostart = [
  "noctalia",
  "swayidle -w before-sleep 'noctalia msg session lock'"
]
mod_key = "Super"
xwayland = true
show_cheatsheet = false
focus_on_activate = false

[workspaces]
back_and_forth = true

[colors]
background = "#141419F0"
text_primary = "#E8E8EAFF"
text_muted = "#8A8A92FF"
accent_primary = "#7AA3FFFF"
accent_secondary = "#F5C96BFF"
warning = "#F5C96BFF"
error = "#FF6B6BFF"

[appearance]
prefer_no_csd = true
border_width = 2               
outer_border_width = 0         
corner_radius = 10             
border_focused = "#7AA3FFFF"
border_unfocused = "#292933FF"
scratchpad_border_focused = "#E5C07BFF"
scratchpad_border_unfocused = "#5C4A2AFF"
outer_border_color = "#1A1A1FFF"
insert_hint_color = "#7FC8FF80"
backdrop_color = "#000000FF"
animation_ms = 200

[appearance.blur]
enabled = true
optimized = true
passes = 3
radius = 5
noise = 0.02
brightness = 0.9
contrast = 0.9
saturation = 2.0

[appearance.shadow]
enabled = true
softness = 39
offset_x = 5
offset_y = 5
color = "#c061cb7F"

[overview]
zoom = 0.5
background_tint = "#10101430"
workspace_background = "#00000044"

[layout]
mode = "scrolling"
gap = 8
width_presets = [0.5, 1.0]

[layout.scrolling]
direction = "horizontal"
default_width_fraction = 0.5
center_underfull_strip = true

[input]
middle_click_paste = true

[input.keyboard]
layout = "us,ru"
options = "grp:win_space_toggle"
repeat_rate = 25
repeat_delay = 600

[input.touchpad]
tap = true
natural_scroll = true

[input.mouse]
accel_profile = "flat"
sensitivity = 0.0

[input.cursor]
theme = "FernBLZ"
size = 24                      
hardware_cursor = true
hide_when_typing = false
hide_timeout_ms = 0

[input.focus]
follows_mouse = true
follows_mouse_max_scroll = 0.0

[keybinds]
# ---Applications---
"Mod+T" = "spawn:wezterm"
"Mod+D" = "spawn:vesktop"
"Mod+E" = "spawn:thunar"
"Mod+Z" = "spawn:AyuGram"
"Mod+W" = "spawn:zen"
"Mod+K" = "spawn:kate"
"Mod+M" = "spawn:pear-desktop"
"F10" = "spawn:qalculate-gtk"
"F11" = "spawn:thunderbird"

# ---Noctalia shell controls---
"Mod+S" = "spawn:noctalia msg panel-toggle launcher"
"Mod+C" = "spawn:noctalia msg panel-toggle control-center"
"F12" = "spawn:noctalia msg panel-toggle session"
"Super+Alt+L" = "spawn:lock-session-kori"

# ---Window actions---
"Mod+Escape" = "window-close"
"Mod+X" = "overview-toggle"
"Mod+F" = "window-cycle-width"
"Mod+Shift+F" = "window-toggle-fullscreen"
"F4" = "window-toggle-fullscreen"
"Mod+V" = "window-toggle-floating"
"Mod+Caps_Lock" = "window-toggle-floating"
"Mod+Space" = "keyboard-layout-next"

# ---Windows Navigation---
"Mod+Left" = "window-focus-left"
"Mod+Right" = "window-focus-right"
"Mod+Up" = "window-focus-up"
"Mod+Down" = "window-focus-down"

#"Mod+H" = "window-focus-left"
#"Mod+L" = "window-focus-right"
#"Mod+J" = "window-focus-down"
#"Mod+K" = "window-focus-up"



"Mod+Shift+Left" = "column-move-left"
"Mod+Shift+Right" = "column-move-right"
"Mod+Shift+Up" = "window-move-up"
"Mod+Shift+Down" = "window-move-down"

#"Mod+Shift+H" = "column-move-left"
#"Mod+Shift+L" = "column-move-right"
#"Mod+Shift+K" = "window-move-up"
#"Mod+Shift+J" = "window-move-down"

# ---Workspaces---
#"Mod+1" = "workspace-1"
#"Mod+2" = "workspace-2"
#"Mod+3" = "workspace-3"
#"Mod+4" = "workspace-4"
#"Mod+5" = "workspace-5"
#"Mod+6" = "workspace-6"
#"Mod+7" = "workspace-7"
#"Mod+8" = "workspace-8"
#"Mod+9" = "workspace-9"

"Mod+Shift+1" = "window-move-to-workspace-1"
"Mod+Shift+2" = "window-move-to-workspace-2"
"Mod+Shift+3" = "window-move-to-workspace-3"
"Mod+Shift+4" = "window-move-to-workspace-4"
"Mod+Shift+5" = "window-move-to-workspace-5"
"Mod+Shift+6" = "window-move-to-workspace-6"
"Mod+Shift+7" = "window-move-to-workspace-7"
"Mod+Shift+8" = "window-move-to-workspace-8"
"Mod+Shift+9" = "window-move-to-workspace-9"

# ---Media keys---
"XF86AudioRaiseVolume" = "spawn:wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1+ -l 1.0"
"XF86AudioLowerVolume" = "spawn:wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1-"
"XF86AudioMute" = "spawn:wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
"XF86AudioMicMute" = "spawn:wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
"XF86AudioPlay" = "spawn:playerctl play-pause"
"XF86AudioNext" = "spawn:playerctl next"
"XF86AudioPrev" = "spawn:playerctl previous"
"XF86MonBrightnessUp" = "spawn:brightnessctl --class=backlight set +10%"
"XF86MonBrightnessDown" = "spawn:brightnessctl --class=backlight set 10%-"

# ---Screenshots toggles---
"Print" = "spawn:noctalia msg screenshot-region" # Screenshot selected region
"Shift+Print" = "spawn:noctalia msg screenshot-fullscreen" # Screenshot full screen

# ---Window rules for Noctalia---
[[window_rule]]
match.app_id = "^dev.noctalia.Noctalia$"
default_floating = true
default_size = [1020, 900]

[[window_rule]]
match.app_id = "^dev.noctalia.UmbrielSharePicker$"
default_floating = true
default_size = [800, 600]

# ---Layer rules for Noctalia shell---
[[layer_rule]]
match.namespace = "^noctalia-(bar-[^\"]+|notification|dock|panel|attached-panel|osd)$"
blur = true
blur_ignore_alpha = 0.5
blur_optimized = false
