name: Update Flake Lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0" # Каждое воскресенье в 03:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      # Проверяем синтаксис флейка ДО обновления лок-файла
      - name: Pre-check flake
        run: nix flake check --no-build

      # Обновляем указанные инпуты и создаем Pull Request
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock-action@v21
        with:
          commit-msg: "chore(flake): update system inputs"
          pr-title: "🔄 Flake.lock: Weekly Inputs Update"
          pr-labels: |
            dependencies
            automated
          inputs: "nixpkgs home-manager" 
          token: ${{ secrets.GITHUB_TOKEN }}
