name: Update Flake Lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

# ВОТ ЭТОТ БЛОК заставит GitHub Actions заткнуться и принудительно включит Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Pre-check flake
        run: nix flake check --no-build

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          commit-msg: "chore(flake): update system inputs"
          pr-title: "🔄 Flake.lock: Weekly Inputs Update"
          pr-labels: |
            dependencies
            automated
          inputs: "nixpkgs home-manager" 
          token: ${{ secrets.GITHUB_TOKEN }}
