name: Update Flake Lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Pre-check flake
        run: nix flake check --no-build

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          commit-msg: "chore(flake): update system inputs"
          pr-title: "🔄 Flake.lock: Weekly Inputs Update"
          pr-labels: |
            dependencies
            automated
          token: ${{ secrets.GITHUB_TOKEN }}
